spring:
  cloud:
    consul:
      config:
        watch:
          enabled: true
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: false
        tags: microservice, infrared
        register-health-check: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  data:
    mongodb:
      authentication-database: admin
      username: viniot
      password: v1niot2019
      host: mongodb
      port: 27017
      database: ir
grpc:
  port: 9000

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

sitewhere:
  client:
    user: admin
    password: password


#spring.cloud.consul.config.watch.enable=true
#spring.cloud.consul.host=171.244.38.133
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.prefer-ip-address=true
#spring.cloud.consul.discovery.tags=template-sitewhere-service
#spring.cloud.consul.discovery.register-health-check=true
#spring.cloud.consul.discovery.instanceId=${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#
#server.port=8888
#
#logging.level.org.springframework.cloud.consul=DEBUG

