version: "3.7"
services:
  mosquitto:
    build: .
    ports:
      - "2883:1883"
      - "9883:9883"
    volumes:
      - ${VOLUME_ROOT}/mosquitto/config:/etc/mosquitto/
      - ${VOLUME_ROOT}/mosquitto/data:/etc/mosquitto/data